# Utilities
[".local/bin/terraform"]
type = "archive-file"
url = "https://releases.hashicorp.com/terraform/1.7.3/terraform_1.7.3_linux_amd64.zip"
path = "terraform"
[".local/bin/gitleaks"]
type = "archive-file"
url = "https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz"
path = "gitleaks"
[".local/bin/.dockcheck"]
type = "archive"
url = "https://github.com/mag37/dockcheck/archive/refs/tags/v0.4.0.zip"
exact = true
stripComponents = 1
include = ["*/*.sh"]
[".local/bin/.xdg-ninja"]
type = "git-repo"
url = "https://github.com/b3nj5m1n/xdg-ninja.git"
refreshPeriod = "168h"
include = ["*/*.sh"]
