# Vim
[".vim/bundle/Vundle.vim"]
type = "archive"
url = "https://github.com/VundleVim/Vundle.vim/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".vim/colors/solarized.vim"]
type = "file"
url = "https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim"
refreshPeriod = "168h"
