# omz Settings
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.20.0.tar.gz"
    exact = true
    stripComponents = 1

# Vim
[".vim/bundle/Vundle.vim"]
    type = "archive"
    url = "https://github.com/VundleVim/Vundle.vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".vim/colors/solarized.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim"
    refreshPeriod = "168h"

# Utilities
[".local/bin/yt-dlp"]
    type = "file"
    url = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp"
    refreshPeriod = "168h"
[".local/bin/terraform"]
    type = "archive-file"
    url = "https://releases.hashicorp.com/terraform/1.7.3/terraform_1.7.3_linux_amd64.zip"
    path = "terraform"
[".local/bin/gitleaks"]
    type = "archive-file"
    url = "https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz"
    path = "gitleaks"
[".local/bin/.dockcheck"]
    type = "archive"
    url = "https://github.com/mag37/dockcheck/archive/refs/tags/v0.4.0.zip"
    exact = true
    stripComponents = 1
    include = ["*/*.sh"]
